export const menuData = {
  indianMainCourseVeg: [
    { name: "Dal Butter Fry", price: "110/-" },
    { name: "Special Dal Makhani", price: "150/-" },
    { name: "Baby Dum Aloo (6 Pcs)", price: "110/-" },
    { name: "Tandoori Aloo Dum", price: "180/-" },
    { name: "Aloo Tikka Labadar (6 Pcs)", price: "150/-" },
    { name: "Corn Palak", price: "60/-" },
    { name: "Mix Veg", price: "160/-" },
    { name: "Mix Veg (Half)", price: "100/-" },
    { name: "Veg Jalfrezi", price: "150/-" },
    { name: "Veg Majedar", price: "220/-" },
    { name: "Mushroom Matar Masala", price: "220/-" },
    { name: "Chana Masala", price: "130/-" },
    { name: "Paneer Butter Masala (Full)", price: "210/-" },
    { name: "Paneer Butter Masala (Half)", price: "120/-" },
    { name: "Paneer Lahori", price: "200/-" },
    { name: "Paneer Kadai", price: "200/-" },
    { name: "Paneer Do Pyaza", price: "220/-" },
    { name: "Malai Kofta Curry (2Pcs)", price: "210/-" },
    { name: "Matar Paneer", price: "160/-" },
    { name: "Matar Paneer (Half)", price: "90/-" },
    { name: "Palak Paneer", price: "150/-" },
    { name: "Paneer Tikka Masala (6Pcs)", price: "200/-" },
  ],
  indianMainCourseNonVeg: [
    { name: "Chicken Curry (4Pcs)", price: "210/-" },
    { name: "Chicken Curry (2Pcs)", price: "110/-" },
    { name: "Chicken Kossa (4Pcs)", price: "220/-" },
    { name: "Chicken Kossa (2Pcs)", price: "140/-" },
    { name: "Chicken Kadai (4Pcs)", price: "250/-" },
    { name: "Chicken Do Pyaza (4Pcs)", price: "250/-" },
    { name: "Chicken Handi (4Pcs)", price: "250/-" },
    { name: "Chicken Handi (2Pcs)", price: "140/-" },
    { name: "Chicken Bharta", price: "230/-" },
    { name: "Chicken Tikka Masala (6Pcs)", price: "250/-" },
    { name: "Chicken Tikka Lababder (6Pcs)", price: "250/-" },
    { name: "Chicken Butter Masala (4Pcs)", price: "320/-" },
    { name: "Chicken Butter Masala (2Pcs)", price: "170/-" },
    { name: "Mutton Curry (4Pcs)", price: "400/-" },
    { name: "Mutton Curry (2Pcs)", price: "220/-" },
    { name: "Mutton Kossa (4Pcs)", price: "420/-" },
    { name: "Mutton Kossa (2Pcs)", price: "230/-" },
    { name: "Mutton Rogan-Josh (4Pcs)", price: "430/-" },
    { name: "Mutton Rogan-Josh (2Pcs)", price: "230/-" },
    { name: "Golbari Mutton Kassa (4 Pcs)", price: "450/-" },
    { name: "Prawns Masala (4 Pcs)", price: "320/-" },
    { name: "Pomfret Masala (1 Pcs)", price: "250/-" },
  ],
  ricePulaoBiryani: [
    { name: "Steam-Rice Full/Half", price: "60/30/-" },
    { name: "Jeera Rice (Bashmati)", price: "120/-" },
    { name: "Veg Pulao (Bashmati)", price: "160/-" },
    { name: "Peas Pulao (Bashmati)", price: "170/-" },
    { name: "Kashmiri Pulao (Bashmati)", price: "220/-" },
    { name: "Basanti Pulao (Gobindobhog)", price: "160/-" },
    { name: "Aloo Biryani (2 Pcs) With Raita", price: "90/-" },
    { name: "Egg Biryani (1 Pcs Egg & Aloo) With Raita", price: "110/-" },
    { name: "Chicken Dum Biryani With Raita", price: "150/-" },
    { name: "Special Chicken Dum Biryani With Raita", price: "200/-" },
    { name: "Mutton Dum Biryani With Raita", price: "240/-" },
    { name: "Special Mutton Dum Biryani With Raita", price: "320/-" },
    { name: "Chicken Chaap (1Pcs)", price: "100/-" },
    { name: "Chicken Rezala (1Pcs)", price: "100/-" },
  ],
  tandooriStarters: [
    { name: "Aloo Nazakat", price: "180/-" },
    { name: "Veg Harabhra Kebab (6Pcs)", price: "180/-" },
    { name: "Paneer Tikka (6 Pcs)", price: "220/-" },
    { name: "Pahari Paneer Tikka (6Pcs)", price: "180/-" },
    { name: "Paneer Malai Tikka (6 Pcs)", price: "220/-" },
    { name: "Veg Seekh Kabab", price: "150/-" },
    { name: "Tandoori Chicken (Half)", price: "250/-" },
    { name: "Tandoori Chicken Full", price: "450/-" },
    { name: "Murgh Tikka (6Pcs)", price: "240/-" },
    { name: "Murgh Malai Kebab (6 Pcs)", price: "240/-" },
    { name: "Murgh Banjara Kebab (6Pcs)", price: "240/-" },
    { name: "Murgh Reshmi Kebab (6 Pcs)", price: "260/-" },
    { name: "Murgh Seekh Kebab (6 Pcs)", price: "240/-" },
    { name: "Fish Tikka - Vetki (4Pcs)", price: "340/-" },
    { name: "Tandoori Pomfret (1 Pcs)", price: "240/-" },
    { name: "Tandoori Prawns (4 Pcs)", price: "300/-" },
    { name: "Murgh Dhani Lanka Special Kebab", price: "340/-" },
    { name: "Chef Special Kebab (6Pcs)", price: "340/-" },
  ],
  chinese: [
    { name: "Crispy Chilli Baby Corn", price: "160/-" },
    { name: "Crispy Honey Chilli Potato", price: "150/-" },
    { name: "American Corn Salt & Pepper", price: "160/-" },
    { name: "Lat Mei Kai", price: "240/-" },
    { name: "Korean Chicken Popcorn", price: "250/-" },
    { name: "Crispy Fried Wings (6Pcs)", price: "260/-" },
    { name: "Drums Of Heaven (6Pcs)", price: "250/-" },
    { name: "Chicken Manchurian (6 Pcs)", price: "180/-" },
    { name: "Chicken Chilli (8 Pcs)", price: "230/-" },
    { name: "Fish Manchurian (6 Pcs)", price: "300/-" },
    { name: "Prawns Chilli (6 Pcs)", price: "300/-" },
    { name: "Hakka Noodles (Chicken)", price: "160/-" },
    { name: "Fried Rice (Chicken)", price: "170/-" },
  ],
  beverages: [
    { name: "Cold Drinks", price: "40/-" },
    { name: "Fresh Lime Soda", price: "70/-" },
    { name: "Mango Lassi", price: "120/-" },
    { name: "Milk Shake", price: "160/-" },
    { name: "Green Mojito", price: "120/-" },
    { name: "Blue Lagoon", price: "120/-" },
    { name: "Pina Colada", price: "135/-" },
  ]
};